import { Navbar } from "@/components/Navigation/Navbar";
import { Sidebar } from "@/components/Navigation/Sidebar";
import { TooltipProvider } from "@/components/ui/tooltip";
import { FrameSettingsProvider } from "@/contexts/FrameSettingsContext";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <TooltipProvider>
          <FrameSettingsProvider>
            <Navbar />
            <Sidebar />
            <main className="ml-16 mt-16">{children}</main>
          </FrameSettingsProvider>
        </TooltipProvider>
      </body>
    </html>
  );
}
